export const FETCH_MOST_SEARCH_TAG_SUCCESS = 'FETCH_MOST_SEARCH_TAG_SUCCESS';

// search
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const SEARCH_AGAIN_BLOG = 'SEARCH_AGAIN_BLOG';

export const UPDATE_HISTORY_TAG = 'UPDATE_HISTORY_TAG';
