export const FETCH_MOST_SEARCH_TAG_SUCCESS = 'FETCH_MOST_SEARCH_TAG_SUCCESS';

// search
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const SEARCH_AGAIN_BLOG = 'SEARCH_AGAIN_BLOG';

export const UPDATE_HISTORY_TAG = 'UPDATE_HISTORY_TAG';

export const FETCH_CONTENT_START = 'FETCH_CONTENT_START';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAILURE = 'FETCH_CONTENT_FAILURE';
